### DISCUSSION TITLE
Custom Validation for schema attributes

### DISCUSSION THREAD

**Discussion by arvindand** [openapi-processor/openapi-processor-spring#223] [Q&A] [answered]
Hi, I went through the documentation but could only find a guide for a custom validation annotation on the bean, is there a plan to support adding custom validation annotations in the generated models for the attributes of a bean?

**Comment by hauner** [comment]
there is no existing plan. If we come up with a usable configuration I can probably add it.

Can you provide an example what you have in mind?  



a few quick thoughts. 

I can think of two possibilities to configure this:

- adding extension properties to the OpenAPI description  and configure a mapping from the extension to an annotation.

Maybe like this
```
# mapping.yaml

map:
  extensions:
    x-custom-validation @ custom.annotation.Validation
```

or 
- allow to configure annotations for `object` properties

```
map:
  object:
     SomeOpenApiObject:
         somePropertyOfTheObject @ custom.annotation.Validation
```

I guess the first would be nice to have that information in the api description. The second could be nice for implementation details.

**Reply by arvindand** [reply]
That's a good question...I think I would still prefer the first option because a feature like this would help in reusing custom property validations across beans and not associating with business logic of a specific type/model. And as you already mentioned, it keeps it part of the api spec.

Perhaps something like this,

  properties:
    exampleProp:
      type: string
      maxLength: 20
      x-constraints:
        - "capitalized"
        - "isbn"
        
     mapping.yaml -->   
        
    map:
      extensions:
        x-constraints:
          - "capitalized" => @custom.validation.Capitalized
          - "isbn" => @custom.validation.Isbn

**Reply by hauner** [reply]
yes, using list for multiple constraints makes sense :)

**Comment by hauner** [comment, marked as answer]
summarizing, it could work like this:

```yaml
components:
  schemas:
    Foo:
      type: object
      properties:
        bar:
          type: string
          maxLength: 10
          x-constraints-1: "constraint"
          x-constraints-2:
            - "foo"
            - "bar"
```

and then map it to annotations with:

```yaml
map:
  extensions:
    - x-constraints-1 @ some.custom.Constraint
    - x-constraints-2:
      - foo @ some.custom.FooConstraint
      - bar @ some.custom.BarConstraint
```
