### DISCUSSION TITLE
combination of result and single/multi for spring webflux

### DISCUSSION THREAD

**Discussion by astmuc** [openapi-processor/openapi-processor-spring#232] [Q&A] [answered]
Is there a way to achieve result types like
```java
Mono<ResponseEntity<SomeBean>>
```
instead of 
```java
ResponseEntity<Mono<SomeBean>> 
```

I need to set header properties in the response (e.g. Etag) which depend on the result processing (SomeBean).
Currently i use this mapping.yaml snippet
```yaml
map:
  result: org.springframework.http.ResponseEntity

  single: reactor.core.publisher.Mono
  multi: reactor.core.publisher.Flux
```

**Comment by hauner** [comment, marked as answer]
I understand that this will not work because the `eTag()` depends on the result of `SomeBean`:

```java
return ResponseEntity.ok ()
     .eTag("foo")
     .body (result of SomeBean);
```

which is a `ResponseEntity<Mono<SomeBean>>`

and you would like to do something like this:

```java
return someBean.getResult()
       .map(r -> ResponseEntity.ok()
       .eTag(r.getEtag())
       .body(r));
```

which is a `Mono<ResponseEntity<SomeBean>>`


There is currently no *official* feature to switch the order of `Mono`/`ResponseEntity`. 

Anyway,  there are two workarounds

#### `Object` workaround 

```yaml
  paths:
    /some-bean-endpoint:
      get:
        types:
          - type: SomeBean => java.lang.Object
        result: plain
```

this uses *official* features and will produce a `Mono<Object>` result. `result: plain` removes the `ResponseEntity` and the type mapping maps the result to `Object`.

You can now return `Mono<ResponseEntity<SomeBean>>` (or anything else) from the controller. 

Works but loses the type information. Which may not be a problem because, usually we do not call the controller from code.

#### `single`/`result` workaround

it is possible to switch the target classes of `single` and `result`. This is not a wanted feature so I consider this a bit *dirty*...

```yaml
map:
  paths:
    /some-bean-endpoint:
        single: org.springframework.http.ResponseEntity
        result: reactor.core.publisher.Mono
```

it is possible to minimize the effect to a specific http method

```yaml
map:
  paths:
    /some-bean-endpoint:
      get: # http method
        single: org.springframework.http.ResponseEntity
        result: reactor.core.publisher.Mono
```


#### disabling `single`/`result`:

this does not apply to this case but it may help with other edge cases.

one can disable the `single` and `result` wrappers for an endpoint by setting one (or both) to `plain`:

```yaml
  paths:
    /some-bean-endpoint:
        single: plain
        result: plain
```
