### ISSUE TITLE
Additional parameter configuration not working in global context

### ISSUE THREAD

**Issue by RobinQu** [openapi-processor/openapi-processor-spring#140]
Example configuration:

```
map:
  types:
    - type: array => java.util.List
  result: org.springframework.http.ResponseEntity
  parameters:
    - add: request => javax.servlet.http.HttpServletRequest
```

Genearted source will not include HttpServletRequest as additional parameter. 

In another attempt with path mapping, it works as documented.

```
map:
  paths:
    /applicants:
      parameters:
        - add: request => javax.servlet.http.HttpServletRequest
```

oap-spring version: 2022.2
