### ISSUE TITLE
Support Spring Boot 3 & Jakarta EE 9

### ISSUE THREAD

**Issue by bergac** [openapi-processor/openapi-processor-spring#152]
Ola!

It would be nice if support for Spring Boot 3 & Jakarta EE 9 is added.

- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes

Spring Boot 3 updated to Jakarta EE 9. The eclipse foundation moved most of the `javax.*` namespace to `jakarta.*`.
To be able to use Spring Boot 3 with models generated by openapi-processor, it needs to use the `jakarta.*` namespace.

**Comment by hauner** [comment]
I didn't know that. Thanks for mentioning it. :-)

This seem to effect only the bean validation annotations so I guess I will change the configuration a little bit to select the `javax` or `jakarta` namespace.

```
openapi-processor-spring: v2.2

options:
 # old javax validations
  bean-validation: true
 # new: javax validations
  bean-validation: v2
 # new: jakarta validations
  bean-validation: v3
```

**Comment by hauner** [comment]
or even better and simpler would be 

```
openapi-processor-spring: v2.2

options:
  bean-validation: javax
  # or
  bean-validation: jakarta
```
