### ISSUE TITLE
description will not be used as javadoc when having custom type mapping

### ISSUE THREAD

**Issue by Snap252** [openapi-processor/openapi-processor-spring#160]
having custom annotation will lead to breaking javadoc generation

having:

```
openapi-processor-mapping: v3

options:
  package-name: xxx
  bean-validation: true
  javadoc: true

map:
  types:
   - type: string:date-time => java.time.OffsetDateTime
```

and
```
title: DatumGesendet
x-stoplight:
  id: nzlj4zrmsiwoh
type: object
description: 'Zeitpunkt, zu dem die Nachricht vom Benutzer an das System übergeben wurde.'
properties:
  datumGesendet:
    type: string
    format: date-time
    description: 'Zeitpunkt, zu dem die Nachricht vom Benutzer an das System übergeben wurde.'
required:
  - datumGesendet
```

will generate:
```
    @NotNull
    @JsonProperty("datumGesendet")
    private OffsetDateTime datumGesendet;
```

without that `string:date-time => java.time.OffsetDateTime`:

```
    /** Zeitpunkt, zu dem die Nachricht vom Benutzer an das System übergeben wurde. */
    @NotNull
    @JsonProperty("datumGesendet")
    private OffsetDateTime datumGesendet;
```
