### ISSUE TITLE
mono/flux validation

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-spring#229]
validation on `Flux<Dto>` only works with the `@Valid` at the `Flux<>` and not on the dto object.

i.e. it requires 

```java
@Valid Flux<Dto>
```

instead of

```java
Flux<@Valid Dto>
```

**Comment by hauner** [comment]
a workaround for *small* request bodies may be to disable the flux ... 

```yaml
map:
  # enabling mono/flux 
  single: reactor.core.publisher.Mono
  multi: reactor.core.publisher.Flux

  types:
    - type: array => java.util.Collection
 
 # disable the flux 
  paths:
    /books:
      post:
        multi: plain
```
