### ISSUE TITLE
upgrade the spring-validation function for Spring Boot 3.x

### ISSUE THREAD

**Issue by baoxingjie** [openapi-processor/openapi-processor-spring#293]
https://github.com/openapi-processor/openapi-processor-samples/blob/master/samples/spring-validation/gradle/libs.versions.toml 

In Spring Boot 3.x, due to the migration of Jakarta EE to Jakarta Namespace, javax.validation has been replaced by jakarta.validation. 
As a result, by default, Spring Boot 3.x cannot directly use classes from the javax.validation package, such as javax.validation.ConstraintValidator and javax.validation.ConstraintValidatorContext. 
Their Jakarta equivalents are jakarta.validation.ConstraintValidator and jakarta.validation.ConstraintValidatorContext.

**Comment by hauner** [comment]
That's right,

the sample you link to is using Spring Boot 2, i.e. `javax`. Setting `bean-validation: true` in the `mapping.yaml` is the same as `bean-validation: javax`. 

For Spring Boot 3 you would use `bean-validation: jakarta`.

Summary of the `bean-validation`option: https://openapiprocessor.io/spring/processor/configuration.html#_bean_validation

The `..boot-3..`  samples enable `jakarta` bean-validation in their corresponding `mapping.yaml` like this:

```yaml
openapi-processor-mapping: v9

options:
  package-name: io.openapiprocessor.samples

  # use bean validations with jakarta package name
  bean-validation: jakarta
```
